### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by caxapexac** [Raais/ImStudio#9] opened 2021-11-29 16:56 UTC
Open program

Press Window

Press Beginchild

Press Button

... Profit :)

**Comment by caxapexac** [comment] 2021-11-29 20:30
Windows 10 Pro 64-bit
Intel Core i7 @ 2.60GHz
Gtx 3060

Took build from https://github.com/Raais/ImStudio/actions?workflow=windows

**Comment by caxapexac** [comment] 2021-11-29 20:31
Can't compile from sources cuz can't install glfw into your cmakelists, can you provide build of compilation steps please?

**Comment by Raais** [comment] 2021-11-29 21:56
I have just checked the [latest build artifact](https://github.com/Raais/ImStudio/actions/runs/1462634666) for Windows and I can't seem to reproduce the same error or crash.
![Capture](https://user-images.githubusercontent.com/64605172/143949123-e61813c6-f328-4f84-9813-7374b0b804de.PNG)

If you do want to build it yourself, you need to have git, CMake and MSVC installed (preferable to have these in your PATH but I have provided absolute path)

GLFW will be automatically downloaded by CMake during build.

In cmd:

```cmd
"C:\Program Files\Git\bin\git.exe" clone https://github.com/Raais/ImStudio
cd ImStudio
md build
cd build
"C:\Program Files\CMake\bin\cmake.exe" .. -DCMAKE_BUILD_TYPE=Release
"C:\Program Files\CMake\bin\cmake.exe" --build . --config Release
```

When the compilation is complete, the executable will be in build\src\Release\ImStudio.exe

**Comment by caxapexac** [comment] 2021-11-29 22:24
Looks like random bug
Try to press [begin child - button (n times) - end child] several times
It worked for me now from 5th time

**Comment by Raais** [comment] 2021-11-29 22:37
It looks like you are using the build from this workflow (older commit with the bug you are referring to).
![Screenshot_2021-11-30_03-29-24](https://user-images.githubusercontent.com/64605172/143953520-f7876d9b-e675-43f6-be9e-609d50f667c2.png)
Am I correct?

**Comment by caxapexac** [comment] 2021-11-30 01:22
Oh now I see, other ones are the artifacts too >_<
Sorry for taking your time
I'll try the newest one asap tomorrow

**Comment by Raais** [comment] 2021-11-30 06:18
No worries. I have deleted the older workflow runs to avoid confusion. Closing this.

**Closed by Raais** 2021-11-30 06:18 UTC

**Comment by caxapexac** [comment] 2021-11-30 16:19
@Raais suggest you to make a release, windows artifacts button is almost invisible now)

**Comment by Raais** [comment] 2021-11-30 17:19
Binaries should now be available [here](https://github.com/Raais/ImStudio/releases/tag/v1.1.1).
